apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: monitoring-testing-october24
  namespace: monitoring-testing-october24
spec:
  rules:
  - host: front.literate-cod-rw6jq5vp4rfpr47.github.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: query-frontend
            port:
              name: http
  tls:
  - hosts:
    - front.literate-cod-rw6jq5vp4rfpr47.github.dev
    secretName: tls-secret